#create makefile

pro_dir := .
output_name := tinhtong
compiler := gcc

src := $(pro_dir)/main.c
src += $(pro_dir)/src/tt.c
src += $(pro_dir)/src/tt1.c
src += $(pro_dir)/src/nhapmang.c
src += $(pro_dir)/src/maxmin.c

inc := $(pro_dir)/inc


build_3:
	@echo "-----------> build_3"
	$(compiler) $(src) -I$(inc) -o tinhtong_3